engines:
  rubocop:
    enabled: true
  bundler-audit:
    enabled: true
  fixme:
    enabled: true
ratings:
   paths:
     - app/**
     - lib/**
     - spec/**
     - "**.rb"
exclude_paths:
  - vendor/**/*