language: ruby

sudo: false

cache: bundler

script:
  - bundle exec rspec spec
  - bundle exec rubocop

addons:
  postgresql: '9.4'
  code_climate:
    repo_token: 05e106c5792bf5cbfe937973a33a356a766b159d5a0ebbbe50144432d92d68ab

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

notifications:
  email:
    on_success: never
    on_failure: change

deploy:
  provider: heroku
  api_key:
    secure: z+FQan/OC5U30mheoy8CCn6Ri5qmLWpuJ/witud0rdqRoRaN5egRkV9r3RIWlSFHR3p4qQmTmI4R83BPycTKYxgDHuqo1p+ey1RD4aJD+/Y3bXpiB1L1QPxpbnxfQ4+8saNqYN0LJI/oSg+U6fTcwrbTZpsxdqDQgkY/yKafaxtie/6gutfWE7u+PzFwQMGXNDjtnCcK0hdy/pCBm2VJDd2F/iPfPC5A1BmRyNeQlLNtBfDN1amBi6jJJD73jy4GvlOrvqK8/iKMt5sYGUndSQFK/HT+4HD/MXFt61JReKORaOHvAdg5mJOdsRUBjt5mLb8Q37Oyu9NcqQ2f0WRAJ8Q3JH08JZUXBvrR8j0UUOIXF0y8Sr4xw7y1Il3IDkvW0TWiu+54+NkmyZCBava48mhOxsXhtFdGf738lTQ8Tz5nxypSVejSPDGQzh37kv+p8NHeEgxKkxzW5sk6u4uUBgUarO+R9aX00C5h09TmFFTJb4lD5lX5dDCiMk/+8ZuLT8FMmBdH8YBZUKagyQf6liSpoGVAZTwbd0GRzUUfDa9K/ETavi+xNsseVH3fxA4DKJsJLcz5u4P3lFT34hr2L2vAmEmAelWt6wSerYVRXQVr8WnNVhIZVItB3ZmumfbCYL2/GaZjJAweCzcrHzOz8zBw+HJBIg3v/wVSbzaHSh4=
  app:
    master: matsrietdijk-api
